trigger:
- main

pool: 
    name: Default

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet Build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
