trigger:
- main

#pool: 
#    name: Default 
pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest', etc.


variables:
    buildconfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
    displayname:'dotnet build $(buildConfiguration)'
